"""
Train the BPE tokenizer used by the emotional-support MiniGPT model.

The tokenizer is trained from the corpus generated by data.py and
saved as tokenizer.json.
"""

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers import normalizers
from tokenizers.pre_tokenizers import (
    Sequence,
    Whitespace,
    Punctuation
)

print("Building tokenizer...")

tokenizer = Tokenizer(
    BPE(
        unk_token="[UNK]"
    )
)

# ==========================================================
# Normalization
# ==========================================================

tokenizer.normalizer = normalizers.Sequence(
    [
        normalizers.NFD(),
        normalizers.StripAccents()
    ]
)

# ==========================================================
# Pre-tokenization
# ==========================================================

tokenizer.pre_tokenizer = Sequence(
    [
        Whitespace(),
        Punctuation()
    ]
)

# ==========================================================
# Trainer
# ==========================================================

trainer = BpeTrainer(
    vocab_size=16000,
    min_frequency=2,
    special_tokens=[
        "[PAD]",
        "[UNK]",
        "[BOS]",
        "[EOS]",
        "<RESPONSE>",
        "User:",
        "Assistant:",
        "Emotion:",
        "Problem:",
        "Strategy:"
    ]
)

# ==========================================================
# Train
# ==========================================================

tokenizer.train(
    ["data/tokenizer_corpus.txt"],
    trainer=trainer
)

# ==========================================================
# Save
# ==========================================================

tokenizer.save(
    "tokenizer.json"
)

print(
    "\nTokenizer Saved!"
)

print(
    "Vocabulary Size:",
    tokenizer.get_vocab_size()
)

# ==========================================================
# Verification
# ==========================================================

tokenizer = Tokenizer.from_file(
    "tokenizer.json"
)

text = """
Emotion: anxiety
Problem: studies
Strategy: Reflection of feelings

User: I failed my exam.

Assistant:

<RESPONSE>

That sounds really difficult.
"""

encoded = tokenizer.encode(
    text
)

print(
    "\nToken Count:",
    len(encoded.ids)
)

print(
    "\nTokens:\n"
)

print(
    encoded.tokens[:100]
)

print(
    "\nToken IDs:\n"
)

print(
    encoded.ids[:100]
)

# ==========================================================
# Additional Test
# ==========================================================

test_text = (
    "I feel overwhelmed and anxious "
    "about my future."
)

encoded = tokenizer.encode(
    test_text
)

print(
    "\nTest Sentence:"
)

print(
    test_text
)

print(
    "\nToken Count:",
    len(encoded.ids)
)

print(
    "\nTokens:"
)

print(
    encoded.tokens
)